[version]
  current = "v5.9.3"

[settings]
  defaultChain = "mainnet"
  cachePath = "/cache"
  indexPath = "/unchained"

[keys]
  [keys.etherscan]
    apiKey = "RF6Z521XGTT83IWYUV6F1U93RCM419MYMX"

[chains]
  [chains.mainnet]
    chain = "mainnet"
    chainId = "1"
    symbol = "ETH"
    rpcProviders = ["https://1.rpc.hypersync.xyz/b5c5baee-7507-451c-bcfb-f0d1e790a5ab"]
    remoteExplorer = "https://etherscan.io"
    safetyDistance = 128
    blockTimeMs = 12000
